-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[spupdateMaterial]
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
    -- Insert statements for procedure here
	-- select * from SMITEMMS
	truncate table SMITEMMS
	insert into SMITEMMS 
	SELECT [code]
      ,[old_code]
      ,[category]
      ,[issue_date]
      ,[yield_range]
      ,[yield_percent]
      ,[lead_time]
      ,[total_shelf_life]
      ,[shelf_life]
      ,[description1]
      ,[description2]
      ,[description3]
      ,[controller]
      ,[product_hierarchy]
      ,[product_name]
      ,[remark1]
      ,[remark2]
      ,[remark3]
      ,[remark4]
      ,[remark5]
      ,[gross_weight]
      ,[net_weight]
      ,[size_dimension]
      ,[material_group]
      ,[smrnumms_id]
      ,[customer_code]
      ,[smcotlms_id]
      ,[smgrp1ms_id]
      ,[smspcsms_id]
      ,[smgrdems_id]
      ,[smctyems_id]
      ,[smcszems_id]
      ,[maximun]
      ,[minimun]
      ,[is_allergen]
      ,[condition_story]
      ,[material_type]
      ,[unit]
      ,[batch_it]
      ,[value_class]
      ,[app_unit]
      ,[max_los]
      ,[conv_f]
      ,[classif]
      ,[mode]
      ,[weight_unit]
      ,[volume]
      ,[volume_unit]
      ,[length]
      ,[width]
      ,[height]
      ,[dim_unit]
      ,[qc_flag]
      ,[update_date]
      ,[fish_compoment]
      ,[ds_limit_qty]
      ,[ns_limit_qty]
      ,[f_fish]
      ,[f_byproduct]
      ,[fish_source]
      ,[labor_hr]
      ,[f_manual]
      ,[f_other_meat]
      ,[plant]
      ,[incubation]
      ,[inspection]
      ,[f_no_gen_psl]
      ,[note1]
      ,[f_manual_plan]
      ,[note2]
      ,[note3]
      ,[f_check_plan]
      ,[f_show_plan_report]
      ,[smpaksms_id]
      ,[bp_type]
      ,[Dia]
      ,[Pack]
      ,[CODE_GROUP]
      ,[CLASSIFICATION]
      ,[Characteristic_1]
      ,[Characteristic_2]
      ,[Characteristic_3]
      ,[Characteristic_4]
      ,[Characteristic_5]
      ,[Characteristic_6]
      ,[Characteristic_7]
      ,[Characteristic_8]
      ,[Characteristic_9]
      ,[Characteristic_10]
      ,[Characteristic_11]
      ,[Characteristic_12]
      ,[Characteristic_13]
      ,[Characteristic_14]
      ,[Characteristic_15]
      ,[Characteristic_16]
      ,[Characteristic_17]
      ,[Characteristic_18]
      ,[Characteristic_19]
      ,[Characteristic_20]
      ,[Hight]
      ,[Profitcenter]
      ,[Import_date]
      ,[Import_Time]
      ,[CODE14DIGIT]
      ,[Characteristic_21]
      ,[Characteristic_22]
      ,[Characteristic_23]
      ,[Characteristic_24]
      ,[Characteristic_25]
      ,[Characteristic_26]
      ,[Characteristic_27]
      ,[Characteristic_28]
      ,[Characteristic_29]
      ,[Characteristic_30]
      ,[f_delete]
      ,[f_pd_block_plan]
      ,[f_pd_purchase]
      ,[f_pd_complete]
  FROM [192.168.1.195].[IHUBT01-01_IHUBRE].[dbo].[SMITEMMS]
END
go

